#inherit_from: .rubocop_todo.yml
Style/FrozenStringLiteralComment:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

#日本語でのコメントのため
Style/AsciiComments:
  Enabled: false

MethodLength:
  CountComments: true  # count full line comments?
  Max: 12
# 自動生成されたファイルを対象外にする
AllCops:
  Exclude:
    - 'Gemfile'
    - 'node_modules/**/*'
    - 'bin/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'test/**/*'
    - 'spec/**/*'